apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      type: color-app
  template:
    metadata:
      labels:
        type: color-app
    spec:
     containers:
     - name: webapp-color
       image: ofandoud/hello-httpd:v1
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-color-service	
spec:
  type: LoadBalancer
  selector:
    type: color-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
   
